"""互換シム。本体は sapo_engine。"""
from sapo_engine import (  # noqa: F401
    ONASAPO_STYLES,
    ONASAPO_PACES,
    ONASAPO_PHASES,
    dress_onasapo,
    resolve_style,
    phase_index,
    next_phase,
    prev_phase,
    onasapo_line,
    onasapo_after,
    denial_roast_lines,
    denial_self_line,
    denial_after,
    onasapo_self_line,
    onasapo_react_options,
    tension_pct,
    render_tension_html,
    phase_label,
    render_phase_dots_html,
)
